version: '3.8'
services:
  db:
    image: elasticsearch:7.13.2
    ports:
    - 9200:9200
    - 9300:9300
    environment:
      - "discovery.type=single-node"
  kibana:
    image: kibana:7.13.2
    ports:
    - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://db:9200
  app:
    image: pokemon-as-a-service
    build:
      context: .
    ports:
    - 5000:5000
    environment:
      - ES_HOST=db
    depends_on:
      - db
    restart: always
